"use client"

import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer/indes";
import { usePathname } from "next/navigation";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disable = ["/login", "/register", "/ai", "/ai/quiz"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${bricolage.className} ${geistMono.variable} antialiased bg-[#0F1214]`}
      >
        {!disable.includes(pathname) && <Navbar />}
        {children}
        {!disable.includes(pathname) && <Footer />}
      </body>
    </html>
  );
}
