"use client";

import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer/index";
import { usePathname } from "next/navigation";
import { SessionProvider, useSession } from "next-auth/react";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const disablePaths = ["/login", "/register", "/ai", "/ai/quiz", "/ai/hasil"];

  const isDisabled = disablePaths.some(
    (path) => pathname === path || pathname.startsWith(path + "/")
  );

  return (
    <html lang="en">
      <body
        className={`${bricolage.className} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {!isDisabled && <Navbar  />}
          {children}
          {!isDisabled && <Footer />}
        </SessionProvider>
      </body>
    </html>
  );
}
